version: "3.9"
services:
  web:
    container_name: "ZoMa-LegoTrain"
    build: .
    image: gubee33/zomalegotrain:latest
    ports:
      - "80:80"
    volumes:
      - ../trackConfigs.json:/var/www/prod/trackConfigs.json
    links:
      - mongo
    deploy:
      restart_policy:
        condition: any
  mongo:
    container_name: mongo
    image: arm64v8/mongo:4.4.12
    command: mongod --port 27018
    ports:
      - '27018:27018'
    deploy:
      restart_policy:
        condition: any
  mongo-express:
    image: mongo-express
    deploy:
      restart_policy:
        condition: any
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 'WE4RTsdf!'
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27018/
