name: Deploy Docker

# Controls when the workflow will run
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        uses: ZoMa-Toys/zoma-ssh@v1.1
        id: ssh_connection
        with:
          host: ${{secrets.HOST}}
          user: ${{secrets.USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          cmd: 'rm -rf buildRepo && git clone --branch docker-mongo ${{github.event.repository.clone_url}} buildRepo && export BUILDENV=production && export ME_CONFIG_BASICAUTH_USERNAME=${{secrets.ME_CONFIG_BASICAUTH_USERNAME}} && export ME_CONFIG_BASICAUTH_PASSWORD=${{secrets.ME_CONFIG_BASICAUTH_PASSWORD}} && cd buildRepo && docker-compose build --no-cache web && docker-compose up -d'
