name: Build and Test
on:
  push:
    branches:
     - '*'
     - '!docker-mongo'
  workflow_call:
  workflow_dispatch:

jobs:
  buildTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install frontend
        run: cd frontend && npm install
      - name: build frontend
        run: cd frontend && npm run build
      - name: install backend
        run: cd backend && npm install
      - name: run tests
        run: cd backend && npm test


